@echo off
setlocal enabledelayedexpansion

set "GEN_EXE=E:\Project\libcss\gen_parser.exe"
set "PROP_GEN=E:\Project\libcss\src\parse\properties\properties.gen"
set "OUT_DIR=E:\Project\libcss\src\parse\properties"

echo Looking for properties.gen...
if not exist "%PROP_GEN%" (
    echo ERROR: properties.gen not found at %PROP_GEN%
    exit /b 1
)

echo Generating parser source files...
for /f "usebackq delims=" %%l in ("%PROP_GEN%") do (
    set "line=%%l"
    if not "!line!"=="" (
        if not "!line:~0,1!"=="#" (
            for /f "tokens=1 delims=:" %%a in ("!line!") do (
                set "prop=%%a"
                if not "!prop!"=="" (
                    echo Processing !prop!...
                    "%GEN_EXE%" -o "%OUT_DIR%\autogenerated_!prop!.c" "!line!"
                )
            )
        )
    )
)

echo Done.
pause